api:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /api/v1

api_get_token:
    path:     /api/getToken
    defaults: { _controller: AppBundle:JWT:getToken }

api_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc/api