services:
    app.pagination_manager:
        class: AppBundle\Service\PaginationManager
    app.mail_manager:
        class: AppBundle\Service\MailManager
        arguments:
            - '@swiftmailer.mailer'
            - '@twig'
            - '%mailer_from%'
            - '%mailer_name%'

    file.filesystem_manager:
        class: AppBundle\Service\FilesystemManager
        arguments:
          - "@oneup_flysystem.mount_manager"

    app.answer_repository:
        class: AppBundle\Repository\AnswerRepository
        factory: ["@doctrine", 'getRepository']
        arguments:
          - AppBundle\Entity\Answer
    app.category_repository:
        class: AppBundle\Repository\CategoryRepository
        factory: ["@doctrine", 'getRepository']
        arguments:
          - AppBundle\Entity\Category
    app.image_repository:
        class: AppBundle\Repository\ImageRepository
        factory: ["@doctrine", 'getRepository']
        arguments:
          - AppBundle\Entity\Image
    app.question_repository:
        class: AppBundle\Repository\QuestionRepository
        factory: ["@doctrine", 'getRepository']
        arguments:
          - AppBundle\Entity\Question

    app.pre_persist_listener:
        class: AppBundle\EventListener\PrePersistListener
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }

    app.image_subscriber:
        class: AppBundle\EventSubscriber\ImageSubscriber
        arguments: ['@twig.extension.httpfoundation', '@file.filesystem_manager']
        tags:
            - { name: doctrine.event_subscriber, connection: default }
