AppBundle\Entity\Answer:
    exclusion_policy: ALL
    properties:
        shortId:
            groups: [answer_simple, question_detailed]
            serializedName: id
        createdAt:
            groups: [answer_admin]
        updatedAt:
            groups: [answer_admin]
        status:
            groups: [answer_admin]
        content:
            groups: [answer_simple, question_detailed]
        question:
            groups: [answer_detailed]

