AppBundle\Entity\Image:
    type: entity
    table: images
    repositoryClass: AppBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        shortId:
            type: shortid
            nullable: false
            generator: { strategy: custom }
            customIdGenerator: { class: PUGX\Shortid\Doctrine\Generator\ShortidGenerator }
        filesystem:
            type: string
            length: 255
            nullable: false
        originalName:
            type: string
            length: 255
            nullable: false
        imageName:
            type: string
            length: 255
            nullable: false
        mimeType:
            type: string
            length: 64
            nullable: false
        size:
            type: integer
            nullable: false
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToOne:
        question:
            targetEntity: AppBundle\Entity\Question
            mappedBy: image
