AppBundle\Entity\Question:
    type: entity
    table: questions
    repositoryClass: AppBundle\Repository\QuestionRepository

    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        shortId:
            type: string
            nullable: false
            unique: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        status:
            type: string
            nullable: false
        content:
            type: string
            nullable: false
    oneToOne:
        image:
            targetEntity: AppBundle\Entity\Image
            mappedBy: question
            cascade: ["persist", "remove"]
        correctAnswer:
            targetEntity: AppBundle\Entity\Answer
            cascade: ["persist"]
            joinColumn:
                name: correct_answer_id
                referencedColumnName: id
                onDelete: cascade
    oneToMany:
        incorrectAnswers:
            targetEntity: AppBundle\Entity\Answer
            mappedBy: question
            cascade: ["persist"]
    manyToOne:
        category:
            targetEntity: AppBundle\Entity\Category
            inversedBy: questions
            joinColumn:
                name: category_id
                referencedColumnName: id
                nullable: false
                onDelete: cascade
